In [58]:
from dotenv import load_dotenv
import os
import urllib
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display, HTML

In [59]:
output_filename=r'output\results_grid_search_2.csv'
# dotenv_path = Path(r'C:\Users\klebi\OneDrive\Documentos\TCC\offshore_ant_web_dev\backend\.env')
# load_dotenv(dotenv_path=dotenv_path)

# DB_user = os.getenv('DB_user')
# DB_password = os.getenv('DB_password')
# DB_name = os.getenv('DB_name')

# # SQLALCHEMY_DATABASE_URL = "sqlite:///./sql_app.db"
# SQLALCHEMY_DATABASE_URL = f"postgresql+psycopg2://{DB_user}:{urllib.parse.quote_plus(DB_password)}@localhost/{DB_name}"

# engine = create_engine(
#     SQLALCHEMY_DATABASE_URL
# )

In [60]:
n_problems = 5
final_grid_search_df = pd.read_csv(output_filename)
# final_grid_search_df['tuple_params'] = list(map(tuple, final_grid_search_df[['n_ants', 'alpha', 'beta', 'rho']].values))

In [61]:
min_10_smallest_df = pd.DataFrame()
for problem_number in range(1, n_problems + 1):
    min_10_smallest_df = pd.concat([min_10_smallest_df, 
                                    (final_grid_search_df.loc[final_grid_search_df['problem_number'] == problem_number]
                                    .nsmallest(10, columns=['best_path_len_downtime', 'time_to_run_sec']))])

In [62]:
# min_10_smallest_df

In [63]:
# min_10_smallest_df

In [64]:
columns = ['best_path_len_downtime', 'time_to_run_sec', 'n_ants', 'alpha', 'beta', 'rho']
for problem_number in range(1, n_problems + 1):
    result_df = min_10_smallest_df.loc[min_10_smallest_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display(result_df)
    display(result_df.agg({'best_path_len_downtime': 'min', 'time_to_run_sec': 'min', 
                           'n_ants': 'mean', 'alpha': 'mean', 'beta': 'mean', 'rho': 'mean'}).to_frame().T)

      best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
660                 9.648711        23.756586       5     10   2.0  0.0
2650                9.856774        12.503579       3      7   2.0  1.0
4495                9.910694        30.032904      10     10   2.0  1.0
5260               10.302916        21.643198       7      3   2.0  1.0
5565               10.330533        30.146724      10      7   2.0  0.0
400                10.344263        15.576077       3      7   2.0  1.0
1210               10.415465         3.922390       1      3   2.0  1.0
5250               10.439317        23.618227       7      3   2.0  0.0
2100               10.441229        37.687896      10      3   2.0  0.0
2020               10.470295        26.265269       7     10   2.0  1.0

   best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
0                9.648711          3.92239     6.3    6.3   2.0  0.6

      best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
3281                5.016922        10.867260      10      5   2.0  1.0
486                 5.022038         8.052569       5      1   2.0  0.5
5116                5.032312         4.382555       5      7   2.0  0.0
2826                5.058847         6.244191       5      5   2.0  0.5
306                 5.087853         4.170496       3      3   2.0  0.5
4981                5.109144         4.448865       5      1   2.0  0.0
5391                5.109667         6.097147       7     10   2.0  0.5
936                 5.151806         9.632876      10      1   2.0  0.5
4261                5.184422         6.057434       7     10   2.0  0.0
3811                5.205096         4.853402       3     10   2.0  0.0

   best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta   rho
0                5.016922         4.170496     6.0    5.3   2.0  0.35

      best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
402                 5.277724         2.795806       3      7   2.0  1.0
5072                5.316482         2.657981       5      5   2.0  0.0
2022                5.316482         5.045262       7     10   2.0  1.0
4267                5.330625         3.740546       7     10   2.0  0.5
1702                5.369382         2.665464       5      5   2.0  0.5
3227                5.369382         8.403002      10      3   2.0  0.0
2967                5.388117         5.784926       7      1   2.0  1.0
3367                5.388117         6.800977      10     10   2.0  0.5
3232                5.388117         8.013542      10      3   2.0  0.5
4317                5.390786         5.302646      10      1   2.0  1.0

   best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
0                5.277724         2.657981     7.4    5.5   2.0  0.6

      best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
4533                4.682924         0.338856       1      1   2.0  0.0
2333                4.682924         0.397164       1      3   2.0  0.5
2338                4.682924         0.429835       1      3   2.0  1.0
4898                4.682924         0.862879       3      7   2.0  0.5
4858                4.682924         0.901658       3      5   2.0  1.0
1563                4.682924         0.970603       3     10   2.0  0.0
2693                4.682924         1.066712       3     10   2.0  0.5
3723                4.682924         1.086912       3      5   2.0  0.0
3678                4.682924         1.135370       3      3   2.0  0.0
3778                4.682924         1.424963       3      7   2.0  1.0

   best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta   rho
0                4.682924         0.338856     2.4    5.4   2.0  0.45

      best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta  rho
4549                4.605105         0.101526       1      3   0.0  0.0
4539                4.605105         0.102112       1      1   2.0  0.5
4584                4.605105         0.104019       1      3   2.0  0.5
4574                4.605105         0.104908       1      3   1.0  1.0
4674                4.605105         0.105266       1      7   2.0  0.5
4569                4.605105         0.108709       1      3   1.0  0.5
4659                4.605105         0.113016       1      7   1.0  0.5
39                  4.605105         0.113111       1      1   2.0  0.5
1224                4.605105         0.115276       1      5   0.0  0.5
4669                4.605105         0.115706       1      7   2.0  0.0

   best_path_len_downtime  time_to_run_sec  n_ants  alpha  beta   rho
0                4.605105         0.101526     1.0    4.0   1.3  0.45

In [65]:
# min_10_smallest_df.to_csv(r'output/smallest_results.csv', index=False)