In [40]:
from dotenv import load_dotenv
import os
import urllib
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display, HTML

In [41]:
algorithm_used = "genetic"
# output_filename=r'output\results_grid_search_2.csv'
output_filename=r'C:\Users\klebi\OneDrive\Documentos\TCC\offshore_ant_web_dev\backend\tests\output\memetic_algo_results_grid_search_with_100_turbines_problems.csv'

In [42]:
n_problems = 6
final_grid_search_df = pd.read_csv(output_filename)
# final_grid_search_df['tuple_params'] = list(map(tuple, final_grid_search_df[['n_ants', 'alpha', 'beta', 'rho']].values))

In [43]:
min_10_smallest_df = pd.DataFrame()
for problem_number in range(1, n_problems + 1):
    min_10_smallest_df = pd.concat([min_10_smallest_df, 
                                    (final_grid_search_df.loc[final_grid_search_df['problem_number'] == problem_number]
                                    .nsmallest(10, columns=['best_path_len_downtime', 'time_to_run_sec']))])

In [44]:
final_grid_search_df

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations,tuple_params
0,1,"['BETA-46', 'BETA-34', 'BETA-04', 'BETA-02', '...","[22, 14, 3, 1, 9, 5, 94, 93, 53, 43, 49, 38, 3...",33.702315,1.871188,35.573503,57.855097,0.1,50,10,"(0.1, 50.0, 10.0)"
1,2,"['BETA-25', 'BETA-18', 'BETA-69', 'BETA-20', '...","[6, 4, 15, 5, 10, 16, 25, 24, 22, 39, 38, 27, ...",10.539275,1.824901,12.364176,36.540993,0.1,50,10,"(0.1, 50.0, 10.0)"
2,3,"['Doca', 'BETA-06', 'BETA-25', 'BETA-22', 'BET...","[0, 1, 3, 2, 4, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.614733,0.513814,4.128547,47.890352,0.1,50,10,"(0.1, 50.0, 10.0)"
3,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 13, 14, 12, 15, 0, 1, 2, 4, ...",3.552320,1.053104,4.605423,16.606490,0.1,50,10,"(0.1, 50.0, 10.0)"
4,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,3.881902,0.1,50,10,"(0.1, 50.0, 10.0)"
...,...,...,...,...,...,...,...,...,...,...,...
103,2,"['BETA-05', 'BETA-09', 'BETA-30', 'BETA-25', '...","[2, 3, 7, 6, 4, 16, 14, 17, 18, 19, 20, 13, 15...",6.404605,1.824901,8.229506,486.077753,0.1,200,30,"(0.1, 200.0, 30.0)"
104,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.576598,0.513814,4.090412,330.656257,0.1,200,30,"(0.1, 200.0, 30.0)"
105,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,152.510537,0.1,200,30,"(0.1, 200.0, 30.0)"
106,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,32.459447,0.1,200,30,"(0.1, 200.0, 30.0)"
107,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,2.267059,0.1,200,30,"(0.1, 200.0, 30.0)"

In [45]:
min_10_smallest_df

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations,tuple_params
24,1,"['BETA-189', 'BETA-127', 'BETA-115', 'BETA-152...","[86, 57, 54, 68, 65, 64, 38, 28, 31, 19, 15, 9...",25.468059,1.870829,27.338888,438.218086,0.1,50,50,"(0.1, 50.0, 50.0)"
48,1,"['BETA-170', 'BETA-212', 'BETA-209', 'BETA-199...","[80, 100, 99, 93, 13, 88, 20, 33, 36, 38, 37, ...",25.549106,1.870470,27.419576,303.777822,0.1,100,40,"(0.1, 100.0, 40.0)"
54,1,"['BETA-139', 'BETA-152', 'BETA-58', 'BETA-56',...","[63, 68, 28, 26, 87, 99, 98, 18, 52, 53, 50, 4...",26.041628,1.870111,27.911739,423.525569,0.1,100,50,"(0.1, 100.0, 50.0)"
12,1,"['BETA-138', 'BETA-133', 'BETA-134', 'BETA-92'...","[62, 60, 61, 42, 43, 58, 56, 55, 68, 69, 75, 8...",26.433765,1.869752,28.303517,162.089032,0.1,50,30,"(0.1, 50.0, 30.0)"
102,1,"['BETA-162', 'BETA-161', 'BETA-160', 'BETA-154...","[75, 74, 73, 69, 71, 90, 50, 5, 7, 97, 88, 92,...",26.509427,1.870470,28.379897,416.807295,0.1,200,30,"(0.1, 200.0, 30.0)"
18,1,"['BETA-199', 'BETA-200', 'BETA-205', 'BETA-202...","[93, 94, 97, 95, 82, 23, 18, 57, 90, 89, 85, 3...",27.530353,1.407966,28.938319,359.517898,0.1,50,40,"(0.1, 50.0, 40.0)"
84,1,"['BETA-26', 'BETA-31', 'BETA-08', 'BETA-02', '...","[10, 12, 6, 1, 98, 96, 90, 24, 54, 59, 64, 44,...",27.150395,1.870470,29.020865,578.689392,0.1,150,50,"(0.1, 150.0, 50.0)"
78,1,"['BETA-84', 'BETA-77', 'BETA-74', 'BETA-17', '...","[38, 36, 35, 9, 92, 89, 30, 29, 44, 62, 68, 73...",27.172396,1.870111,29.042508,440.574483,0.1,150,40,"(0.1, 150.0, 40.0)"
72,1,"['BETA-58', 'BETA-06', 'BETA-07', 'BETA-27', '...","[28, 4, 5, 11, 35, 32, 34, 36, 29, 44, 57, 62,...",28.355215,1.870829,30.226044,304.610008,0.1,150,30,"(0.1, 150.0, 30.0)"
36,1,"['BETA-132', 'BETA-159', 'BETA-164', 'BETA-209...","[59, 72, 76, 99, 24, 31, 30, 50, 27, 52, 44, 8...",28.497996,1.870829,30.368825,138.115523,0.1,100,20,"(0.1, 100.0, 20.0)"
19,2,"['BETA-25', 'BETA-30', 'BETA-05', 'BETA-09', '...","[6, 7, 2, 3, 8, 1, 0, 38, 39, 9, 11, 12, 36, 3...",5.622303,1.929315,7.551618,460.692192,0.1,50,40,"(0.1, 50.0, 40.0)"
55,2,"['BETA-141', 'BETA-135', 'BETA-149', 'BETA-137...","[28, 25, 30, 26, 27, 29, 31, 21, 32, 33, 40, 3...",5.502655,2.478651,7.981305,391.269643,0.1,100,50,"(0.1, 100.0, 50.0)"
25,2,"['BETA-18', 'BETA-20', 'BETA-69', 'BETA-74', '...","[4, 5, 15, 16, 14, 17, 18, 19, 20, 13, 10, 36,...",6.291294,1.929315,8.220608,617.734558,0.1,50,50,"(0.1, 50.0, 50.0)"
103,2,"['BETA-05', 'BETA-09', 'BETA-30', 'BETA-25', '...","[2, 3, 7, 6, 4, 16, 14, 17, 18, 19, 20, 13, 15...",6.404605,1.824901,8.229506,486.077753,0.1,200,30,"(0.1, 200.0, 30.0)"
79,2,"['BETA-05', 'BETA-09', 'BETA-01', 'BETA-33', '...","[2, 3, 1, 8, 7, 6, 4, 5, 10, 15, 16, 14, 17, 1...",6.428498,1.824901,8.253399,475.903416,0.1,150,40,"(0.1, 150.0, 40.0)"
85,2,"['BETA-09', 'BETA-01', 'BETA-33', 'BETA-40', '...","[3, 1, 8, 9, 39, 38, 0, 40, 34, 35, 32, 33, 29...",6.823221,1.823466,8.646687,627.990848,0.1,150,50,"(0.1, 150.0, 50.0)"
43,2,"['BETA-198', 'BETA-205', 'BETA-40', 'BETA-62',...","[38, 39, 9, 13, 12, 11, 36, 24, 22, 30, 29, 26...",6.187082,2.476498,8.663580,250.844932,0.1,100,30,"(0.1, 100.0, 30.0)"
97,2,"['BETA-161', 'BETA-158', 'BETA-174', 'BETA-172...","[33, 32, 35, 34, 40, 0, 39, 38, 36, 37, 24, 25...",6.594359,2.476498,9.070857,205.591917,0.1,200,20,"(0.1, 200.0, 20.0)"
49,2,"['BETA-18', 'BETA-20', 'BETA-25', 'BETA-09', '...","[4, 5, 6, 3, 1, 7, 39, 0, 11, 12, 2, 8, 9, 38,...",7.213577,1.928956,9.142533,246.871918,0.1,100,40,"(0.1, 100.0, 40.0)"
37,2,"['BETA-05', 'BETA-30', 'BETA-40', 'BETA-52', '...","[2, 7, 9, 11, 12, 36, 25, 27, 24, 28, 29, 31, ...",7.559125,1.824901,9.384026,111.484426,0.1,100,20,"(0.1, 100.0, 20.0)"
92,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.551748,0.513455,4.065203,85.746117,0.1,200,10,"(0.1, 200.0, 10.0)"
98,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.551748,0.513455,4.065203,200.948607,0.1,200,20,"(0.1, 200.0, 20.0)"
20,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.551748,0.513455,4.065203,219.571701,0.1,50,40,"(0.1, 50.0, 40.0)"
14,3,"['Doca', 'BETA-172', 'BETA-170', 'BETA-167', '...","[0, 18, 17, 16, 19, 20, 13, 15, 14, 12, 11, 10...",3.811349,0.272336,4.083685,114.463968,0.1,50,30,"(0.1, 50.0, 30.0)"
74,3,"['Doca', 'BETA-172', 'BETA-170', 'BETA-167', '...","[0, 18, 17, 16, 19, 20, 13, 15, 14, 12, 11, 10...",3.811349,0.272336,4.083685,253.041709,0.1,150,30,"(0.1, 150.0, 30.0)"
8,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.576598,0.513814,4.090412,71.980094,0.1,50,20,"(0.1, 50.0, 20.0)"
68,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.576598,0.513814,4.090412,154.713690,0.1,150,20,"(0.1, 150.0, 20.0)"
44,3,"['BETA-172', 'BETA-170', 'BETA-167', 'BETA-178...","[18, 17, 16, 19, 20, 13, 15, 14, 12, 11, 10, 9...",3.576598,0.513814,4.090412,167.236935,0.1,100,30,"(0.1, 100.0, 30.0)"
50,3,"['BETA-172', 'BETA-170', 'BETA-167', 'BETA-178...","[18, 17, 16, 19, 20, 13, 15, 14, 12, 11, 10, 9...",3.576598,0.513814,4.090412,217.090449,0.1,100,40,"(0.1, 100.0, 40.0)"
26,3,"['Doca', 'BETA-39', 'BETA-06', 'BETA-25', 'BET...","[0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11, 12, 14,...",3.576598,0.513814,4.090412,246.697292,0.1,50,50,"(0.1, 50.0, 50.0)"
15,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,60.525155,0.1,50,30,"(0.1, 50.0, 30.0)"
39,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,64.511320,0.1,100,20,"(0.1, 100.0, 20.0)"
21,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,93.178743,0.1,50,40,"(0.1, 50.0, 40.0)"
99,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,107.272034,0.1,200,20,"(0.1, 200.0, 20.0)"
75,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,113.705154,0.1,150,30,"(0.1, 150.0, 30.0)"
51,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,116.312573,0.1,100,40,"(0.1, 100.0, 40.0)"
57,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,117.773854,0.1,100,50,"(0.1, 100.0, 50.0)"
81,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,144.764840,0.1,150,40,"(0.1, 150.0, 40.0)"
105,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,152.510537,0.1,200,30,"(0.1, 200.0, 30.0)"
87,4,"['BETA-118', 'BETA-137', 'BETA-136', 'BETA-133...","[7, 11, 10, 9, 8, 6, 5, 3, 14, 13, 12, 15, 0, ...",3.253353,1.052027,4.305380,188.461945,0.1,150,50,"(0.1, 150.0, 50.0)"
4,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,3.881902,0.1,50,10,"(0.1, 50.0, 10.0)"
34,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,6.776812,0.1,100,10,"(0.1, 100.0, 10.0)"
10,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,7.552873,0.1,50,20,"(0.1, 50.0, 20.0)"
64,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,9.187541,0.1,150,10,"(0.1, 150.0, 10.0)"
16,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,10.492324,0.1,50,30,"(0.1, 50.0, 30.0)"
46,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,10.867819,0.1,100,30,"(0.1, 100.0, 30.0)"
94,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,11.685236,0.1,200,10,"(0.1, 200.0, 10.0)"
70,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,14.777280,0.1,150,20,"(0.1, 150.0, 20.0)"
40,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,18.106634,0.1,100,20,"(0.1, 100.0, 20.0)"
58,5,"['Doca', 'BETA-201', 'BETA-152', 'BETA-120', '...","[0, 10, 9, 7, 8, 5, 6, 4, 3, 2, 1, 0]",3.049109,0.481521,3.530631,18.561544,0.1,100,50,"(0.1, 100.0, 50.0)"
5,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,0.380965,0.1,50,10,"(0.1, 50.0, 10.0)"
35,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,0.549931,0.1,100,10,"(0.1, 100.0, 10.0)"
65,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,0.714854,0.1,150,10,"(0.1, 150.0, 10.0)"
11,6,"['BETA-156', 'BETA-120', 'BETA-58', 'BETA-36',...","[4, 3, 2, 1, 0, 5, 4]",2.771295,0.841048,3.612342,0.747519,0.1,50,20,"(0.1, 50.0, 20.0)"
95,6,"['BETA-156', 'BETA-120', 'BETA-58', 'BETA-36',...","[4, 3, 2, 1, 0, 5, 4]",2.771295,0.841048,3.612342,1.075341,0.1,200,10,"(0.1, 200.0, 10.0)"
17,6,"['BETA-156', 'BETA-120', 'BETA-58', 'BETA-36',...","[4, 3, 2, 1, 0, 5, 4]",2.771295,0.841048,3.612342,1.145952,0.1,50,30,"(0.1, 50.0, 30.0)"
41,6,"['BETA-156', 'BETA-120', 'BETA-58', 'BETA-36',...","[4, 3, 2, 1, 0, 5, 4]",2.771295,0.841048,3.612342,1.262025,0.1,100,20,"(0.1, 100.0, 20.0)"
71,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,1.455043,0.1,150,20,"(0.1, 150.0, 20.0)"
23,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,1.549963,0.1,50,40,"(0.1, 50.0, 40.0)"
47,6,"['BETA-201', 'Doca', 'BETA-36', 'BETA-58', 'BE...","[5, 0, 1, 2, 3, 4, 5]",2.771295,0.841048,3.612342,1.701329,0.1,100,30,"(0.1, 100.0, 30.0)"

In [46]:
if algorithm_used in ["genetic", "memetic"]:
    columns = ['best_path_len_downtime', 'time_to_run_sec', 'mutation_rate', 'population_size', 'number_of_generations']
else:
    columns = ['best_path_len_downtime', 'time_to_run_sec', 'n_ants', 'alpha', 'beta', 'rho']

for problem_number in range(1, n_problems + 1):
    result_df = min_10_smallest_df.loc[min_10_smallest_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display(result_df)

    if algorithm_used == "genetic":
        display(result_df.agg({'best_path_len_downtime': 'median', 'time_to_run_sec': 'median', 
                                'mutation_rate': lambda x: x.mode().iloc[0], 'population_size': lambda x: x.mode().iloc[0], 'number_of_generations': lambda x: x.mode().iloc[0]}).to_frame().T)
    else:
        display(result_df.agg({'best_path_len_downtime': 'min', 'time_to_run_sec': 'min', 
                    'n_ants': 'mean', 'alpha': 'mean', 'beta': 'mean', 'rho': 'mean'}).to_frame().T)

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
24,27.338888,438.218086,0.1,50,50
48,27.419576,303.777822,0.1,100,40
54,27.911739,423.525569,0.1,100,50
12,28.303517,162.089032,0.1,50,30
102,28.379897,416.807295,0.1,200,30
18,28.938319,359.517898,0.1,50,40
84,29.020865,578.689392,0.1,150,50
78,29.042508,440.574483,0.1,150,40
72,30.226044,304.610008,0.1,150,30
36,30.368825,138.115523,0.1,100,20

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,28.659108,388.162596,0.1,50.0,30.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
19,7.551618,460.692192,0.1,50,40
55,7.981305,391.269643,0.1,100,50
25,8.220608,617.734558,0.1,50,50
103,8.229506,486.077753,0.1,200,30
79,8.253399,475.903416,0.1,150,40
85,8.646687,627.990848,0.1,150,50
43,8.663580,250.844932,0.1,100,30
97,9.070857,205.591917,0.1,200,20
49,9.142533,246.871918,0.1,100,40
37,9.384026,111.484426,0.1,100,20

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,8.450043,425.980918,0.1,100.0,40.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
92,4.065203,85.746117,0.1,200,10
98,4.065203,200.948607,0.1,200,20
20,4.065203,219.571701,0.1,50,40
14,4.083685,114.463968,0.1,50,30
74,4.083685,253.041709,0.1,150,30
8,4.090412,71.980094,0.1,50,20
68,4.090412,154.713690,0.1,150,20
44,4.090412,167.236935,0.1,100,30
50,4.090412,217.090449,0.1,100,40
26,4.090412,246.697292,0.1,50,50

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,4.087048,184.092771,0.1,50.0,20.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
15,4.30538,60.525155,0.1,50,30
39,4.30538,64.511320,0.1,100,20
21,4.30538,93.178743,0.1,50,40
99,4.30538,107.272034,0.1,200,20
75,4.30538,113.705154,0.1,150,30
51,4.30538,116.312573,0.1,100,40
57,4.30538,117.773854,0.1,100,50
81,4.30538,144.764840,0.1,150,40
105,4.30538,152.510537,0.1,200,30
87,4.30538,188.461945,0.1,150,50

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,4.30538,115.008863,0.1,100.0,30.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
4,3.530631,3.881902,0.1,50,10
34,3.530631,6.776812,0.1,100,10
10,3.530631,7.552873,0.1,50,20
64,3.530631,9.187541,0.1,150,10
16,3.530631,10.492324,0.1,50,30
46,3.530631,10.867819,0.1,100,30
94,3.530631,11.685236,0.1,200,10
70,3.530631,14.777280,0.1,150,20
40,3.530631,18.106634,0.1,100,20
58,3.530631,18.561544,0.1,100,50

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,3.530631,10.680071,0.1,100.0,10.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
5,3.612342,0.380965,0.1,50,10
35,3.612342,0.549931,0.1,100,10
65,3.612342,0.714854,0.1,150,10
11,3.612342,0.747519,0.1,50,20
95,3.612342,1.075341,0.1,200,10
17,3.612342,1.145952,0.1,50,30
41,3.612342,1.262025,0.1,100,20
71,3.612342,1.455043,0.1,150,20
23,3.612342,1.549963,0.1,50,40
47,3.612342,1.701329,0.1,100,30

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,3.612342,1.110646,0.1,50.0,10.0

In [47]:
# min_10_smallest_df.to_csv(r'output/smallest_results.csv', index=False)